use_default_settings: true

default_doi_resolver: ''  # ✅ Corrige l'erreur fatale

server:
  secret_key: "ultrasecretkey"  # 🔐 à changer pour production
  limiter: false
  image_proxy: true

# redis:
#   url: redis://redis:6379/0  # ❌ Désactivé car l'hôte "redis" n'existe pas sur Koyeb
