# SearXNG Settings - Optimized for Railway
use_default_settings: true

general:
  debug: false
  instance_name: "Research SearXNG"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: "google"
  autocomplete_min: 2
  default_lang: "auto"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  base_url: false
  limiter: false
  public_instance: false
  secret_key: "ultrasecretkey12345678901234567890123456789012345678901234567890"
  image_proxy: true
  http_protocol_version: "1.1"
  method: "GET"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

redis:
  url: false

ui:
  static_path: ""
  templates_path: ""
  default_theme: simple
  center_alignment: false
  results_on_new_tab: false
  query_in_title: true
  infinite_scroll: false
  search_on_category_select: true
  hotkeys: default

outgoing:
  request_timeout: 3.0
  max_request_timeout: 10.0
  useragent_suffix: ""
  pool_connections: 20
  pool_maxsize: 10
  enable_http2: false

categories_as_tabs:
  general:
  images:
  videos:
  news:
  maps:
  it:
  science:

engines:
  # Essential search engines only
  - name: google
    engine: google
    shortcut: go
    weight: 2
    
  - name: bing
    engine: bing
    shortcut: bi
    weight: 1.5
    
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    weight: 1.2
    
  - name: startpage
    engine: startpage
    shortcut: sp
    startpage_categ: web
    categories: [general, web]
    
  # Image engines
  - name: google images
    engine: google_images
    shortcut: goi
    
  - name: bing images
    engine: bing_images
    shortcut: bii
    
  # News engines  
  - name: google news
    engine: google_news
    shortcut: gon
    
  - name: bing news
    engine: bing_news
    shortcut: bin
    
  # Video engines
  - name: youtube
    shortcut: yt
    engine: youtube_noapi
    
  - name: google videos
    engine: google_videos
    shortcut: gov
    
  # Developer tools
  - name: github
    engine: github
    shortcut: gh
    
  - name: stackoverflow
    engine: stackexchange
    shortcut: st
    api_site: 'stackoverflow'
    categories: [it, q&a]
    
  # Reference
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    display_type: ["infobox", "list"]
    categories: [general]
    
  # Social
  - name: reddit
    engine: reddit
    shortcut: re
    page_size: 25
    
  # Files & Images
  - name: unsplash
    engine: unsplash
    shortcut: us
    categories: [images]
    
  - name: flickr
    categories: images
    shortcut: fl
    engine: flickr_noapi

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'

default_doi_resolver: 'oadoi.org'
